import type { Metadata } from "next";
import { Anton, Lato } from "next/font/google";
import "./globals.css";

const anton = Anton({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-anton",
});

const lato = Lato({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${anton.variable} ${lato.variable} `}>
      <body>{children}</body>
    </html>
  );
}
